# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: development

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 
      
      - uses: anthonykgross/ansible-vault-cli-github-action@v1
        with: 
          vault_key: '${{ secrets.VAULT_PASSWORD }}'
          command: "ansible-vault decrypt ./inventory/techzone-vm.ini"

      # - uses: anthonykgross/ansible-vault-cli-github-action@v1
      #   with:
      #     command: cat ./inventory/techzone-vm.ini | sed 's/./& /g'
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      
      - name: list host
        run: |
          ansible-inventory -i ./inventory/techzone-vm.ini --list 

      - name: run playbook
        run: |
          ansible-playbook ./playbook/install-docker.yaml -i ./inventory/techzone-vm.ini
          

      # - name: Run playbook
      #   uses: dawidd6/action-ansible-playbook@v2
      #   with:
      #     playbook: ./playbook/install-docker.yaml
      #     directory: ./